dist: trusty
language: node_js
node_js:
  - "node"
cache: npm
install:
  - npm install
  - npm install -g gulp
script:
  - gulp sass
deploy:
  provider: pages,
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
